config/routes.rb
Rails.application.routes.draw do
root 'pages#home'
get 'about', to: 'pages#about'
resources :articles
get 'signup', to: 'users#new'
resources :users, except: [:new]
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get 'logout', to: 'sessions#destroy'
resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105 }, format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]     
   end

   def logged_in?
    !!current_user
  end

  def require_user

    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action!"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
   
  end


  def new
    @article = Article.new
  end

  def edit
  end

  def create
  
    @article = Article.new(article_params)
    @article.user = current_user
   if @article.save
    flash[:notice] = "Article was created successfully!"
    redirect_to @article
   else
    render :new, status: :unprocessable_entity
   end
  end


  def update
   if @article.update(article_params)
    flash[:notice] = "Article was updated succesfully!"
    redirect_to @article
   else
    render 'edit'
   end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

private

def set_article
  @article = Article.find(params[:id])
end

def article_params
  params.require(:article).permit(:title, :description, category_ids: [])
end

def require_same_user
if current_user != @article.user && !current_user.admin?
  flash[:alert] = "You can only edit or delete your own article!"
  redirect_to @article
  end
end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new 
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated succesfully!"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created!"
      redirect_to @category
    else
      render 'new'
    end
  end


private

def category_params
  params.require(:category).permit(:name)
end

def require_admin
  if !(logged_in? && current_user.admin?)
    flash[:alert] = "Only admins can perform that action!"
    redirect_to categories_path
end
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:notice] = "Logged in successfully"
    redirect_to user
  else
    flash.now[:alert] = "Wrong login or password!"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  flash[:notice] = "Logged out"
  redirect_to root_path
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def edit

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Account information successfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}! You have successfully signed up!"
      redirect_to articles_path
    else
      render 'new'
  end
end

def destroy

  @user.destroy
  session[:user_id] = nil if @user == current_user
  flash[:notice] = "Account and all associated articles successfully deleted"
  redirect_to articles_path

end




private
def user_params
  params.require(:user).permit(:username, :email, :password)
end

def set_user
  @user = User.find(params[:id])

end

def require_same_user
  if current_user != @user && !current_user.admin?
    flash[:alert] = "You can only edit or delete your own account!"
    redirect_to @user
end

end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end





end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">

<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
 <div class="col-8 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  <h5 class="card-header fst-italic">
  <% if article.user %>
  by <%= link_to article.user.username, user_path(article.user) %>
  <% end %>
  <% if article.categories.any? %>

  <div class="mt-2"><%= render article.categories %></div>

  <% end %>
  </h5>
 
  <div class="card-body ">
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-decoration-none" %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
   
    <div class = "d-flex justify-content-center flex-md-row gap-3">
    <%= link_to 'View', article_path(article), class: "btn btn-outline-success"  %> 
    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info"  %>
    <%= button_to 'Delete', article_path(article), method: :delete,  data: {confirm: "Are you sure ?"} , "data-turbo": false, class: "btn btn-outline-danger"  %> 
    <% end %>
    </div>
 

  </div>
  <div class = "card-footer text-muted"></div>
</div>
</div>
</div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
<div class=" row justify-content-center ">
<div class="col-9">
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, class:  "shadow  mb-3 bg-success bg-gradient rounded p-3", data: { turbo: false }, local: true)  do |f| %>
  <div class = "form-group row">
    <%= f.label :title, class: "col-2 col-form-label text-light" %>
    <div class = "col-10">
    <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Article title" %>
    </div>
  </div>

  <div class = "form-group row mt-4">
  <%= f.label :description, class: "col-2 col-form-label text-light" %>
  <div class = "col-10">
  <%= f.text_area :description, rows:10, class: "form-control shadow rounded", placeholder: "Article description" %>
  </div>
  </div>

  <div class = "form-group row mt-4">
  <%= f.label :category, class: "col-2 col-form-label text-light" %>
  <div class = "col-10">
  <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below (can be empty)"}, {multiple: true, size: 3, class: "form-select shadow rounded "}) %>
  </div>
  </div>

  <div class = "form-group justify-content-center d-block text-center p-3">
    <%= f.submit  class: "btn btn-outline-light btn-lg" %>
    </div>

  <% end %>
  </div>
  <%= link_to '[Cancel and return to articles listing]', articles_path(@article), class: "text-center  text-decoration-none" %>
  </div>
  </div></div>

app/views/articles/edit.html.erb
<h1 class = "text-center p-3">Edit article</h1>


  <%= render 'form' %>

app/views/articles/index.html.erb
<br>
<br>

<h1 class = "text-center p-3">All Articles List</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>
<p class = "text-center  text-decoration-none" ><%= link_to '[Create new article]', new_article_path %></p>

app/views/articles/new.html.erb
<h1 class = "text-center p-3">Create a new article</h1>



<%= render  'form' %>

app/views/articles/show.html.erb
<br>
<br>

<h2 class = "text-center p-3"><%= @article.title %></h2>

<div class="container">


  <div class="row justify-content-md-center">
 <div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <h5 class="card-header fst-italic">by <%= @article.user.username if @article.user %>
  <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
  <% if @article.categories.any? %>

  <div class="mt-2"><%= render @article.categories %></div>

  <% end %>
  
  </h5>


  <div class="card-body ">
   
 
    <div class="card-text text-start"><%= simple_format(@article.description) %></div>
    <div class = "d-flex justify-content-center flex-md-row gap-3">
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info"  %>
    <%= button_to 'Delete', article_path(@article), method: :delete,  data: {confirm: "Are you sure ?"} , "data-turbo": false, class: "btn btn-outline-danger"  %> 
    <% end %>
    </div>
    

  </div>
  <div class = "card-footer text-muted"></div>
</div>
</div>
</div>

</div>

<p class = "text-center  text-decoration-none" ><%= link_to '[Create new article]', new_article_path %></p>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-decoration-none me-2" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class:  "shadow  mb-3 bg-success bg-gradient rounded p-3", data: { turbo: false }, local: true)  do |f| %>
  <div class = "form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class = "col-10">
    <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name" %>
    </div>
  </div>

 

  <div class = "form-group justify-content-center d-block text-center p-3">
    <%= f.submit  class: "btn btn-outline-light btn-lg" %>
    </div>

  <% end %>

app/views/categories/edit.html.erb
<h1 class = "text-center p-3">Edit category name</h1>

<div class="container">
<div class=" row justify-content-center ">
<div class="col-9">
  <%= render 'form' %>
  </div>
  <%= link_to '[Cancel and return to category]', category_path(@category), class: "text-center  text-decoration-none" %>
  </div>
  </div></div>

app/views/categories/index.html.erb
<h1 class = "text-center p-3">Categories</h1>


<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
 <div class="col-4 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  <div class="card-body ">
    <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success text-decoration-none" %></h5>
    <p class="card-text"><%=pluralize(category.articles.count, "article") %></p>
    </div>
</div>
</div>
</div>
<% end %>
</div>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center p-3">Create a new category</h1>

<div class="container">
<div class=" row justify-content-center ">
<div class="col-9">
  <%= render 'form' %>
  </div>
  <%= link_to '[Cancel and return to categories listing]', categories_path, class: "text-center  text-decoration-none" %>
  </div>
  </div></div>

app/views/categories/show.html.erb
<h1 class = "text-center p-3">Category: <%= @category.name %> </h1>

<div class ="text-center mt-4">
    <% if logged_in? && current_user.admin? %>
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
<% end %>
</div>


<h3 class = "text-center p-3">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
  <% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= msg %>
<% else %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= msg %>
  <% end %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
<div class="container-fluid">
  
  <%= link_to "BLOG APP", root_path, class: "navbar-brand  fw-bolder text-body ", id: "logo" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

   
    <% if logged_in? %>
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-success fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
     <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>] 
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li class="nav-item">
    <%= link_to "View profile", user_path(current_user), class: "nav-link text-body" %>
    </li>
    <li class="nav-item">
    <%= link_to "Edit profile", edit_user_path(current_user),  class: "nav-link text-body" %>
    </li>
    <li class="nav-item">
    <%= button_to "Delete profile", user_path(current_user),  class: "nav-link text-danger btn btn-link", method: :delete, data: {confirm: "Are you sure ?"}, "data-turbo": false %>
   
    </li>
    </ul>
  </li>
  <li class="nav-item">
  <%= link_to 'Logout', logout_path, class: "nav-link fw-bold text-body ",  data: { "turbo-method": :delete} %>
  </li>
    <% else %>
    <li class="nav-item">
    <%= link_to 'Log in', login_path, class: "nav-link fw-bold text-success" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign up', signup_path, class: "nav-link fw-bold text-body" %>
  </li>
    <% end %>
</li>
    <li class="nav-item">
    <%= link_to "Bloggers", users_path, class: "nav-link text-body" %>
  </li>

  <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle text-body" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Articles
  </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
  <% if logged_in? %>
  <li class="nav-item">
  <%= link_to "Create new article", new_article_path, class: "nav-link text-body" %>
  </li>
  <% end %>
  <li class="nav-item">
  <%= link_to "View articles", articles_path,  class: "nav-link text-body" %>
  </li>
  </ul>
</li>

<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle text-body" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Categories
  </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
  <% if logged_in? && current_user.admin? %>
  <li class="nav-item">
  <%= link_to "Create new category", new_category_path, class: "nav-link text-body" %>
  </li>
  <% end %>
  <li class="nav-item">
  <%= link_to "View categories", categories_path,  class: "nav-link text-body" %>
  </li>
  </ul>
</li>
    </ul>
    
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "custom.css", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color:#E3E3E3">
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Articles listing', articles_path(@article) %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="px-4 py-5 my-5 text-center text-bg-secondary p-3">
   <p></p>

    <h1 class="display-5 fw-bold mt-4">BLOG APPLICATION</h1>

    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4"></p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg px-4 gap-3" %>
      </div>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">Following errors occured</h4>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
   <li> <%= msg %> </li>
    <% end %>
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>


<% end %>

app/views/users/_form.html.erb
<div class="container">
<div class=" row justify-content-center ">
<div class="col-9">
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, class:  "shadow  mb-3 bg-success bg-gradient rounded p-3", data: { turbo: false }, local: true)  do |f| %>
  <div class = "form-group row">
    <%= f.label :username, class: "col-2 col-form-label text-light" %>
    <div class = "col-10">
    <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
    </div>
  </div>

  <div class = "form-group row mt-4">
  <%= f.label :email, class: "col-2 col-form-label text-light" %>
  <div class = "col-10">
  <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Email address" %>
  </div>
  </div>

  <div class = "form-group row mt-4">
  <%= f.label :password, class: "col-2 col-form-label text-light" %>
  <div class = "col-10">
  <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
  </div>
  </div>

  <div class = "form-group justify-content-center d-block text-center p-3">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account",  class: "btn btn-outline-light btn-lg") %>
    </div>

  <% end %>
  </div>
  <%= link_to '[Cancel and return to articles listing]', articles_path(@article), class: "text-center  text-decoration-none" %>
  </div>
  </div></div>

app/views/users/edit.html.erb
<h1 class = "text-center p-3">Edit profile</h1>



<%= render  'form' %>

app/views/users/index.html.erb
<h1 class = "text-center p-3">Bloggers list</h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div
<div class="container">
<% @users.each do |user| %>
  <div class="row justify-content-md-center">
 <div class="col-8 mt-4">
<div class="card text-center shadow  mb-5 bg-white rounded">
  <h5 class="card-header fst-italic"><%= link_to user.username, user %></h5>
  <div class="card-body ">
    <h5 class="card-title">
    <%= link_to gravatar_for(user, size:150 ), user  %></h5>
    <p class="card-text"><%=pluralize(user.articles.count, "article") %></p>
   
    <div class = "d-flex justify-content-center flex-md-row gap-3">
    <%= link_to 'View profile', user, class: "btn btn-outline-success"  %> 
    <% if logged_in? %> 
    <% if user == current_user %>
    <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info"  %>
    <% end %>
    <% if current_user.admin? %>
      <%= button_to 'Delete user', user_path(user), method: :delete,  data: {confirm: "Are you sure ?"} , "data-turbo": false, class: "btn btn-outline-danger"  %> 
    <% end %>
    <% end %>
    </div>
  </div>
  <div class = "card-footer text-muted"></div>
</div>
</div>
</div>
<% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class = "text-center p-3">Sign up for BLOG</h1>



<%= render  'form' %>

app/views/users/show.html.erb
<h1 class = "text-center p-3"><%=@user.username%>'s profile</h1>


<%= gravatar_for @user, size: 200 %>

<div class ="text-center mt-4">
    <% if logged_in? && @user == current_user %>
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
<% end %>
</div>


<h3 class = "text-center p-3">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div